version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: quickbook_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quickbook_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - default

volumes:
  postgres_data:
